### ISSUE TITLE
Support for forward velocity

### ISSUE THREAD

**Issue by silentsilas** [SixWays/UnityVrTunnelling#1]
It seems this script is only for rotational velocity; most VR games with tunneling tend to use it mainly for fast movements in any direction. I'll try modifying the script to support this feature and send a pull request if this is desired.

**Comment by silentsilas** [comment]
see #2

**Comment by agamero** [comment]
Thanks to SixWays for sharing this tunneling solution! I also needed to account for position and then saw this (Poeticode) post. I noticed one little bug in this updated solution though. The effect doesn't reset after movement because position isn't reset. Easy fix, just add 
_lastPos = pos;
at the bottom of Update.
